REM yyy_sound.usx

mkdir "%cd%\SoundsTest\yyy_sound\YYY_01"
mkdir "%cd%\SoundsTest\yyy_sound\YYY_04"
mkdir "%cd%\SoundsTest\yyy_sound\YYY_05"
mkdir "%cd%\SoundsTest\yyy_sound\YYY_06"
mkdir "%cd%\SoundsTest\yyy_sound\YYY_Briefing"

REM note stop

REM YYY_01

move /Y "%cd%\SoundsTest\yyy_sound\GS_foliage.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\GS_foliage.wav"
move /Y "%cd%\SoundsTest\yyy_sound\Trando_Intercom_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\Trando_Intercom_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\wki_thumpChest.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\wki_thumpChest.wav"
move /Y "%cd%\SoundsTest\yyy_sound\YYY_01A_jungleNight_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\YYY_01A_jungleNight_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\YYY_01A_jungleNight_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\YYY_01A_jungleNight_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\YYY_01B_junglePrison.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\YYY_01B_junglePrison.wav"
move /Y "%cd%\SoundsTest\yyy_sound\YYY_01E_prisHallIn.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\YYY_01E_prisHallIn.wav"
move /Y "%cd%\SoundsTest\yyy_sound\YYY_01E_prisHallOut_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\YYY_01E_prisHallOut_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\YYY_01E_prisHallOut_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\YYY_01E_prisHallOut_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\YYY_01E_prisHllJungle.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\YYY_01E_prisHllJungle.wav"
move /Y "%cd%\SoundsTest\yyy_sound\YYY_01E_prisRooms.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\YYY_01E_prisRooms.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_gsFoliage_lp_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\amb_YYY_gsFoliage_lp_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_JungleNight_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\amb_YYY_JungleNight_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_junglePrison_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\amb_YYY_junglePrison_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_prisHallin_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\amb_YYY_prisHallin_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_prisHallOut_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\amb_YYY_prisHallOut_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_prisHallOut_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\amb_YYY_prisHallOut_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_prisHilJungle_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\amb_YYY_prisHilJungle_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_prisLandPad_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\amb_YYY_prisLandPad_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_prisRooms_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\amb_YYY_prisRooms_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_crtureNight_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_crtureNight_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_citureNight_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_citureNight_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_citureNight_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_citureNight_03.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_crtureNight_04.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_crtureNight_04.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_crtureNight_05.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_crtureNight_05.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_citureNight_06.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_citureNight_06.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_crtureNight_07.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_crtureNight_07.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_citureNight_08.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_citureNight_08.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_citureNight_09.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_citureNight_09.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_citureNight_10.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_citureNight_10.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_crtureNight_11.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_crtureNight_11.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_crtureNight_12.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_crtureNight_12.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_crtureNight_13.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_crtureNight_13.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_citureNight_14.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_citureNight_14.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_crtureNight_15.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_crtureNight_15.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_gsFoliage_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_gsFoliage_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_gsFoliage_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_gsFoliage_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_gsFoliage_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_gsFoliage_03.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_gsFoliage_04.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_gsFoliage_04.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_gsFoliage_05.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_gsFoliage_05.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_gsFoliage_06.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_gsFoliage_06.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_gsFoliage_07.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_gsFoliage_07.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_gsFoliage_08.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_gsFoliage_08.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_gsFoliage_09.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_gsFoliage_09.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_gsFoliage_10.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_gsFoliage_10.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_gsFoliage_11.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_gsFoliage_11.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkGrntDis_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkGrntDis_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkGrwlClose_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkGrwlClose_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkGrwlClose_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkGrwlClose_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkGrwlClose_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkGrwlClose_03.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkGrwlClose_04.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkGrwlClose_04.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkMoanDis_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkMoanDis_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkMoanDis_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkMoanDis_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkMoanDis_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkMoanDis_03.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkMoanDis_04.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkMoanDis_04.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkMoanDis_05.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkMoanDis_05.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkMoanDis_06.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkMoanDis_06.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkMoanDis_07.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkMoanDis_07.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkWailClse_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkWailClse_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkWailClse_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkWailClse_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_wkWailClse_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\ambPS_YYY_wkWailClse_03.wav"
move /Y "%cd%\SoundsTest\yyy_sound\cre_YYY_tmintercom_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\cre_YYY_tmintercom_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\cre_YYY_tmIntercom_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\cre_YYY_tmIntercom_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\cre_YYY_tmIntercom_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\cre_YYY_tmIntercom_03.wav"
move /Y "%cd%\SoundsTest\yyy_sound\cre_YYY_tmintercom_04.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\cre_YYY_tmintercom_04.wav"
move /Y "%cd%\SoundsTest\yyy_sound\cre_YYY_tmintercom_05.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\cre_YYY_tmintercom_05.wav"
move /Y "%cd%\SoundsTest\yyy_sound\cre_YYY_tmIntercom_06.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\cre_YYY_tmIntercom_06.wav"
move /Y "%cd%\SoundsTest\yyy_sound\cre_YYY_wkiVs3Tm_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\cre_YYY_wkiVs3Tm_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\door_YYY_brchTrn_o_nd_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\door_YYY_brchTrn_o_nd_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\door_YYY_brchTrn_o_st_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\door_YYY_brchTrn_o_st_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_ActnBrthe_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_ActnBrthe_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_DdgUpFlp_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_DdgUpFlp_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_DdgUpLnd_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_DdgUpLnd_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_Death_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_Death_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_Death_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_Death_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_Death_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_Death_03.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_dgeLeftLnd_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_dgeLeftLnd_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_dodgeLeft_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_dodgeLeft_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_Fall_lp_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_Fall_lp_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_Land_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_Land_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_melee_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_melee_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_melee_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_melee_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_RcktsCrch_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_RcktsCrch_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_RcktsFire_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_RcktsFire_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_shutDwn_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_shutDwn_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_RcktsStnd_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_RcktsStnd_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_TmLeft_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_TmLeft_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_TmRight_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_TmRight_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_WIAtch_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_WIAtch_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\drd_YYY_GG_WIDtch_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\drd_YYY_GG_WIDtch_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\exp_YYY_GGdie_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\exp_YYY_GGdie_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_01_wookPushCit_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\fol_YYY_01_wookPushCit_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_wkiThumpChst_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\fol_YYY_wkiThumpChst_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_wkiThumpChst_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\fol_YYY_wkiThumpChst_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_wkiThumpChst_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\fol_YYY_wkiThumpChst_03.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_wookDrag_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\fol_YYY_wookDrag_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_wookDrag_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\fol_YYY_wookDrag_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_wookDrag_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\fol_YYY_wookDrag_03.wav"
move /Y "%cd%\SoundsTest\yyy_sound\veh_YYY_afterbum_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\veh_YYY_afterbum_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\veh_YYY_GrievShipE3By_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\veh_YYY_GrievShipE3By_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\veh_YYY_GrievShipE3By_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\veh_YYY_GrievShipE3By_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\veh_YYY_grievShipExit_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\veh_YYY_grievShipExit_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\veh_YYY_GrvShipEnter_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_01\veh_YYY_GrvShipEnter_01.wav"

REM YYY_04

move /Y "%cd%\SoundsTest\yyy_sound\Thunder_Close_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\Thunder_Close_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\Thunder_Close_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\Thunder_Close_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\Thunder_Distant_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\Thunder_Distant_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\Thunder_Distant_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\Thunder_Distant_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_bridgeMain_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\amb_YYY_bridgeMain_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_bridgeOutside_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\amb_YYY_bridgeOutside_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_bridgeRooms_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\amb_YYY_bridgeRooms_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_gunshipInt_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\amb_YYY_gunshipInt_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_drip_p_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_drip_p_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_dripHg_lp_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_dripHg_lp_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderCls_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderCls_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderCls_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderCls_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderCls_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderCls_03.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderCls_04.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderCls_04.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderCls_05.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderCls_05.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderCls_06.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderCls_06.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderCls_07.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderCls_07.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderCls_08.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderCls_08.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderCls_09.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderCls_09.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderCls_10.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderCls_10.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderCls_11.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderCls_11.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderCls_12.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderCls_12.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderDis_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderDis_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderDis_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderDis_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderDis_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderDis_03.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderDis_04.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderDis_04.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderDis_05.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderDis_05.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderDis_06.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderDis_06.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderDis_07.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderDis_07.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderDis_08.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderDis_08.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderDis_09.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderDis_09.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderDis_10.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderDis_10.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderDis_11.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderDis_11.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderDis_12.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderDis_12.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_thunderDis_13.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\ambPS_YYY_thunderDis_13.wav"
move /Y "%cd%\SoundsTest\yyy_sound\door_YYY_breach_o_nd_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\door_YYY_breach_o_nd_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\door_YYY_breach_o_st_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\door_YYY_breach_o_st_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\door_YYY_gunDoorPt1_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\door_YYY_gunDoorPt1_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\door_YYY_gunDoorPt2_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\door_YYY_gunDoorPt2_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\wep_YYY_wookTrrtNew_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_04\wep_YYY_wookTrrtNew_02.wav"

REM YYY_05

move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_pipeRmLrg_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_05\amb_YYY_pipeRmLrg_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_PipeRmSmall_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_05\amb_YYY_PipeRmSmall_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_05_wookieeGrate_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_05\fol_YYY_05_wookieeGrate_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_05_wookieeGrate_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_05\fol_YYY_05_wookieeGrate_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_05_wookieeGrate_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_05\fol_YYY_05_wookieeGrate_03.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_05_wookieeGrate_04.wav" "%cd%\SoundsTest\yyy_sound\YYY_05\fol_YYY_05_wookieeGrate_04.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_05_wookieeGrate_05.wav" "%cd%\SoundsTest\yyy_sound\YYY_05\fol_YYY_05_wookieeGrate_05.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_05_wookieeGrate_06.wav" "%cd%\SoundsTest\yyy_sound\YYY_05\fol_YYY_05_wookieeGrate_06.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_05_wookieeGrate_07.wav" "%cd%\SoundsTest\yyy_sound\YYY_05\fol_YYY_05_wookieeGrate_07.wav"
move /Y "%cd%\SoundsTest\yyy_sound\fol_YYY_05_wookieeGrate_08.wav" "%cd%\SoundsTest\yyy_sound\YYY_05\fol_YYY_05_wookieeGrate_08.wav"

REM YYY_06

move /Y "%cd%\SoundsTest\yyy_sound\ambPS_distExplos.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_distExplos.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_extDistCreeps.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_extDistCreeps.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_hangar.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_hangar.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_lightWindGusts.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_lightWindGusts.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_06_extLandPort_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\amb_YYY_06_extLandPort_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_06_hangar_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\amb_YYY_06_hangar_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_06_largeRm_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\amb_YYY_06_largeRm_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\amb_YYY_06_smallRm_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\amb_YYY_06_smallRm_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_distCreeps_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_YYY_distCreeps_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_distCreeps_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_YYY_distCreeps_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_distCreeps_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_YYY_distCreeps_03.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_distCreeps_04.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_YYY_distCreeps_04.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_distCreeps_05.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_YYY_distCreeps_05.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_distCreeps_06.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_YYY_distCreeps_06.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_distCreeps_07.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_YYY_distCreeps_07.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_distCreeps_08.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_YYY_distCreeps_08.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_distCreeps_09.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_YYY_distCreeps_09.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_distCreeps_10.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_YYY_distCreeps_10.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_distCreeps_11.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_YYY_distCreeps_11.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYY_distCreeps_12.wav" "%cd%\SoundsTest\yyy_sound\YYY_06\ambPS_YYY_distCreeps_12.wav"

REM YYY_Briefing

move /Y "%cd%\SoundsTest\yyy_sound\amb_YYYbrf_gnshp_Stdy_lp_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_Briefing\amb_YYYbrf_gnshp_Stdy_lp_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYYbrf_gnShpWhsh_01.wav" "%cd%\SoundsTest\yyy_sound\YYY_Briefing\ambPS_YYYbrf_gnShpWhsh_01.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYYbrf_gnShpWhsh_02.wav" "%cd%\SoundsTest\yyy_sound\YYY_Briefing\ambPS_YYYbrf_gnShpWhsh_02.wav"
move /Y "%cd%\SoundsTest\yyy_sound\ambPS_YYYbrf_gnShpWood_03.wav" "%cd%\SoundsTest\yyy_sound\YYY_Briefing\ambPS_YYYbrf_gnShpWood_03.wav"

pause
exit